import type { Config } from 'tailwindcss';

/** Auto-generated from Stitch htmlCode tailwind-config — do not hand-edit colors. */
const config: Config = {
  "darkMode": "class",
  "content": [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/stitch-screens/**/*.{js,ts,jsx,tsx}"
  ],
  "theme": {
    "extend": {
      "colors": {
        "on-primary": "#003914",
        "tertiary-container": "#9ea2a0",
        "on-tertiary": "#2d3130",
        "surface-container": "#1b211f",
        "inverse-surface": "#dee4e0",
        "on-background": "#dee4e0",
        "primary-container": "#1db954",
        "on-primary-container": "#004118",
        "tertiary-fixed": "#e0e3e1",
        "secondary-fixed": "#e5deff",
        "error": "#ffb4ab",
        "primary-fixed": "#72fe8f",
        "surface": "#0f1513",
        "surface-tint": "#53e076",
        "surface-container-lowest": "#090f0e",
        "inverse-primary": "#006e2d",
        "error-container": "#93000a",
        "inverse-on-surface": "#2c322f",
        "surface-container-high": "#252b29",
        "on-surface-variant": "#bccbb9",
        "on-secondary-container": "#baaeff",
        "tertiary-fixed-dim": "#c4c7c5",
        "on-error": "#690005",
        "secondary": {
          "DEFAULT": "#c9bfff",
          "foreground": "hsl(var(--secondary-foreground))"
        },
        "surface-variant": "#303634",
        "tertiary": "#c4c7c5",
        "primary": {
          "DEFAULT": "#53e076",
          "foreground": "hsl(var(--primary-foreground))"
        },
        "surface-bright": "#343a38",
        "secondary-fixed-dim": "#c9bfff",
        "on-secondary-fixed": "#1a0063",
        "on-secondary": "#2e009c",
        "surface-container-low": "#171d1b",
        "on-primary-fixed-variant": "#005320",
        "primary-fixed-dim": "#53e076",
        "on-surface": "#dee4e0",
        "surface-dim": "#0f1513",
        "on-tertiary-container": "#353937",
        "outline-variant": "#3d4a3d",
        "outline": "#869585",
        "on-error-container": "#ffdad6",
        "on-primary-fixed": "#002108",
        "on-tertiary-fixed-variant": "#444846",
        "background": "#0f1513",
        "surface-container-highest": "#303634",
        "on-secondary-fixed-variant": "#441cc8",
        "on-tertiary-fixed": "#181c1b",
        "secondary-container": "#4720ca",
        "border": "hsl(var(--border))",
        "input": "hsl(var(--input))",
        "ring": "hsl(var(--ring))",
        "foreground": "hsl(var(--foreground))",
        "card": {
          "DEFAULT": "hsl(var(--card))",
          "foreground": "hsl(var(--card-foreground))"
        },
        "destructive": {
          "DEFAULT": "hsl(var(--destructive))",
          "foreground": "hsl(var(--destructive-foreground))"
        },
        "muted": {
          "DEFAULT": "hsl(var(--muted))",
          "foreground": "hsl(var(--muted-foreground))"
        },
        "success": {
          "DEFAULT": "hsl(var(--success))",
          "foreground": "hsl(var(--success-foreground))"
        },
        "warning": {
          "DEFAULT": "hsl(var(--warning))",
          "foreground": "hsl(var(--warning-foreground))"
        }
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding": "24px",
        "card-padding": "16px"
      },
      "fontFamily": {
        "headline-md": [
          "Outfit"
        ],
        "body-lg": [
          "Outfit"
        ],
        "display-tr-mobile": [
          "Outfit"
        ],
        "display-tr": [
          "Outfit"
        ],
        "caption": [
          "Outfit"
        ],
        "body-md": [
          "Outfit"
        ],
        "headline-lg": [
          "Outfit"
        ],
        "data-value": [
          "JetBrains Mono"
        ],
        "data-label": [
          "JetBrains Mono"
        ]
      },
      "fontSize": {
        "headline-md": [
          "24px",
          {
            "lineHeight": "32px",
            "fontWeight": "600"
          }
        ],
        "body-lg": [
          "18px",
          {
            "lineHeight": "28px",
            "fontWeight": "400"
          }
        ],
        "display-tr-mobile": [
          "32px",
          {
            "lineHeight": "40px",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ],
        "display-tr": [
          "48px",
          {
            "lineHeight": "56px",
            "letterSpacing": "-0.02em",
            "fontWeight": "700"
          }
        ],
        "caption": [
          "12px",
          {
            "lineHeight": "16px",
            "fontWeight": "500"
          }
        ],
        "body-md": [
          "16px",
          {
            "lineHeight": "24px",
            "fontWeight": "400"
          }
        ],
        "headline-lg": [
          "30px",
          {
            "lineHeight": "38px",
            "fontWeight": "600"
          }
        ],
        "data-value": [
          "16px",
          {
            "lineHeight": "20px",
            "fontWeight": "700"
          }
        ],
        "data-label": [
          "14px",
          {
            "lineHeight": "20px",
            "letterSpacing": "0.05em",
            "fontWeight": "500"
          }
        ]
      },
      "boxShadow": {
        "brand-glow": "0 0 40px rgba(255, 107, 74, 0.15)"
      }
    }
  },
  "plugins": [],
  "safelist": [
    "-top-3",
    "-translate-x-1/2",
    "-translate-y-1/2",
    "-z-10",
    "absolute",
    "active:scale-90",
    "ambient-glow",
    "animate-pulse",
    "backdrop-blur-md",
    "backdrop-blur-xl",
    "bg-[#0A0E0D]",
    "bg-[#7B61FF]",
    "bg-black/40",
    "bg-error",
    "bg-gradient-to-b",
    "bg-gradient-to-t",
    "bg-primary",
    "bg-primary-container",
    "bg-primary/10",
    "bg-primary/100",
    "bg-primary/20",
    "bg-primary/40",
    "bg-primary/50",
    "bg-primary/60",
    "bg-primary/80",
    "bg-primary/90",
    "bg-secondary",
    "bg-secondary-container",
    "bg-secondary-container/20",
    "bg-surface-container",
    "bg-surface-container-high",
    "bg-surface-container-low",
    "bg-surface-container-lowest",
    "bg-surface-variant",
    "bg-surface/80",
    "bg-transparent",
    "bg-white/10",
    "blur-[120px]",
    "border",
    "border-b",
    "border-collapse",
    "border-error/20",
    "border-l",
    "border-l-2",
    "border-outline",
    "border-outline-variant",
    "border-primary",
    "border-primary/30",
    "border-primary/50",
    "border-r",
    "border-r-4",
    "border-secondary-container/30",
    "border-secondary/20",
    "border-secondary/30",
    "border-secondary/50",
    "border-t",
    "border-white/10",
    "border-white/20",
    "border-white/5",
    "bottom-0",
    "bottom-4",
    "col-span-1",
    "complex",
    "cursor-pointer",
    "dark:bg-surface-container-lowest",
    "dark:bg-surface/80",
    "dark:text-primary-fixed",
    "duration-200",
    "duration-300",
    "emerald-glow",
    "fixed",
    "flex",
    "flex-1",
    "flex-col",
    "flex-wrap",
    "focus:border-primary",
    "focus:outline-none",
    "focus:ring-1",
    "focus:ring-primary",
    "font-body-lg",
    "font-body-md",
    "font-bold",
    "font-caption",
    "font-data-label",
    "font-data-value",
    "font-display-tr",
    "font-display-tr-mobile",
    "font-headline-lg",
    "font-headline-md",
    "font-medium",
    "font-semibold",
    "from-background",
    "from-surface-container-lowest",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-6",
    "gap-8",
    "gap-stack-lg",
    "gap-stack-md",
    "glass-card",
    "glass-overlay",
    "glass-panel",
    "glow-hover",
    "grid",
    "grid-cols-1",
    "group",
    "group-focus-within:text-primary",
    "group-hover:bg-primary/10",
    "group-hover:bg-primary/30",
    "group-hover:bg-primary/50",
    "group-hover:bg-primary/70",
    "group-hover:brightness-110",
    "group-hover:opacity-100",
    "h-1.5",
    "h-1/3",
    "h-1/4",
    "h-10",
    "h-12",
    "h-16",
    "h-2",
    "h-2/4",
    "h-20",
    "h-24",
    "h-3/4",
    "h-48",
    "h-5/6",
    "h-6",
    "h-64",
    "h-8",
    "h-[800px]",
    "h-[calc(100vh-80px)]",
    "h-full",
    "h-screen",
    "heatmap-grid",
    "hidden",
    "hm-high",
    "hm-low",
    "hm-mid",
    "hm-severe",
    "hover:-translate-y-1",
    "hover:bg-primary",
    "hover:bg-primary/10",
    "hover:bg-primary/30",
    "hover:bg-surface-bright",
    "hover:bg-surface-container",
    "hover:bg-white/5",
    "hover:bg-white/[0.02]",
    "hover:border-error/50",
    "hover:border-primary",
    "hover:border-primary/50",
    "hover:border-secondary/50",
    "hover:brightness-110",
    "hover:opacity-100",
    "hover:text-on-primary",
    "hover:text-on-surface",
    "hover:text-primary",
    "hover:text-primary-fixed",
    "hover:text-white",
    "inline-block",
    "inline-flex",
    "inset-0",
    "italic",
    "items-baseline",
    "items-center",
    "items-end",
    "items-start",
    "justify-between",
    "justify-center",
    "left-0",
    "left-1/2",
    "left-3",
    "left-4",
    "material-symbols-outlined",
    "max-w-2xl",
    "max-w-4xl",
    "max-w-5xl",
    "max-w-7xl",
    "mb-1",
    "mb-16",
    "mb-2",
    "mb-4",
    "mb-6",
    "mb-8",
    "mb-stack-lg",
    "md:block",
    "md:col-span-4",
    "md:col-span-6",
    "md:col-span-8",
    "md:flex",
    "md:flex-row",
    "md:font-display-tr",
    "md:gap-8",
    "md:grid-cols-12",
    "md:grid-cols-3",
    "md:h-96",
    "md:hidden",
    "md:items-end",
    "md:mb-0",
    "md:ml-64",
    "md:pb-container-padding",
    "md:text-display-tr",
    "min-h-[320px]",
    "min-h-[921px]",
    "min-h-screen",
    "ml-64",
    "mt-1",
    "mt-2",
    "mt-20",
    "mt-4",
    "mt-8",
    "mt-auto",
    "mt-stack-md",
    "mx-2",
    "mx-auto",
    "object-cover",
    "opacity-0",
    "opacity-50",
    "opacity-80",
    "overflow-hidden",
    "overflow-x-auto",
    "overflow-y-auto",
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "p-6",
    "p-card-padding",
    "p-container-padding",
    "pb-3",
    "pb-32",
    "pb-4",
    "pb-safe",
    "pl-10",
    "placeholder:text-on-surface-variant",
    "pointer-events-none",
    "pr-4",
    "pr-96",
    "pt-4",
    "pt-stack-md",
    "px-2",
    "px-3",
    "px-4",
    "px-6",
    "px-8",
    "px-container-padding",
    "px-gutter",
    "py-0.5",
    "py-1",
    "py-1.5",
    "py-2",
    "py-24",
    "py-3",
    "py-4",
    "py-6",
    "py-stack-lg",
    "relative",
    "right-0",
    "rounded",
    "rounded-full",
    "rounded-lg",
    "rounded-md",
    "rounded-r-md",
    "rounded-sm",
    "rounded-t-sm",
    "rounded-xl",
    "scale-105",
    "scale-95",
    "shadow-[-10px_0_30px_rgba(0,0,0,0.5)]",
    "shadow-[0_0_10px_#53e076]",
    "shadow-[0_0_10px_rgba(123,97,255,0.4)]",
    "shadow-[0_0_10px_rgba(83,224,118,0.2)]",
    "shadow-[0_0_10px_rgba(83,224,118,0.5)]",
    "shadow-[0_0_15px_rgba(29,185,84,0.1)]",
    "shadow-[0_0_15px_rgba(29,185,84,0.3)]",
    "shadow-[0_0_15px_rgba(83,224,118,0.2)]",
    "shadow-[0_0_20px_rgba(29,185,84,0.3)]",
    "shadow-[0_0_20px_rgba(83,224,118,0.1)]",
    "shadow-[0_0_5px_#53e076]",
    "shadow-[0_0_5px_rgba(83,224,118,1)]",
    "shadow-[0_0_8px_#53e076]",
    "sheen-top",
    "sm:flex-row",
    "space-x-1",
    "space-y-1",
    "space-y-2",
    "space-y-3",
    "space-y-4",
    "space-y-stack-lg",
    "sparkline-svg",
    "sticky",
    "text-2xl",
    "text-[10px]",
    "text-[11px]",
    "text-[12px]",
    "text-[14px]",
    "text-[16px]",
    "text-[18px]",
    "text-[20px]",
    "text-[32px]",
    "text-body-lg",
    "text-body-md",
    "text-caption",
    "text-center",
    "text-data-label",
    "text-data-value",
    "text-display-tr-mobile",
    "text-error",
    "text-gradient",
    "text-headline-lg",
    "text-headline-md",
    "text-left",
    "text-on-primary",
    "text-on-primary-fixed",
    "text-on-secondary-container",
    "text-on-surface",
    "text-on-surface-variant",
    "text-primary",
    "text-right",
    "text-secondary",
    "text-secondary-container",
    "text-sm",
    "text-tertiary",
    "text-tertiary-container",
    "text-white",
    "text-xs",
    "to-black",
    "to-transparent",
    "top-0",
    "top-1/2",
    "top-20",
    "tracking-tighter",
    "tracking-wide",
    "tracking-wider",
    "tracking-widest",
    "transform",
    "transition-all",
    "transition-colors",
    "transition-opacity",
    "transition-transform",
    "translate-x-0",
    "translate-x-1",
    "uppercase",
    "via-transparent",
    "w-1.5",
    "w-1/6",
    "w-10",
    "w-12",
    "w-16",
    "w-2",
    "w-20",
    "w-64",
    "w-8",
    "w-[22%]",
    "w-[360px]",
    "w-[65%]",
    "w-[8%]",
    "w-[800px]",
    "w-full",
    "w-px",
    "z-10",
    "z-30",
    "z-40",
    "z-50"
  ]
};

export default config;
